### ISSUE TITLE
Support for `MPS` devices

### ISSUE THREAD

**Issue by bigcat88** [liusida/ComfyUI-AutoCropFaces#6]
Can be here added a check if the `MPS` device present and if it is then use it instead of CUDA?

And if there is no CUDA or MPS then fallback to `cpu`..

https://github.com/liusida/ComfyUI-AutoCropFaces/blob/30c0007ee6aea7637aa2bf730958f0c57699aedb/__init__.py#L63

P.S: Thank you for this Node

**Comment by liusida** [comment]
hi @bigcat88 , why did you close this issue? It sounds like a valid feature request, doesn't it? Should I reopen it?

**Comment by liusida** [comment]
ok, i've changed the default device from "cuda" to "auto" 
https://github.com/liusida/ComfyUI-AutoCropFaces/commit/e92d5f4cc4f43a4b8935e263a197b17a4417f059

And I've just learned that device "cpu" is fast enough for this inference.

PS: "mps" is not tested, since I don't have a Mac. I assume it would have no problems but it'll still be nice to have someone who can actually test it.

**Comment by liusida** [comment]
> hi @bigcat88 , why did you close this issue? It sounds like a valid feature request, doesn't it? Should I reopen it?

I now know the reason. xD

I was trying to encourage others to get involved...
